In [1]:
print('hi')

hi


In [2]:
import torch

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

/Users/kandanai/anaconda3/envs/torch-env/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


Using device: cpu


In [ ]:
## 2D Tensors

# Create tensors
a = torch.tensor([2.0, 3.0], device=device)
b = torch.tensor([4.0, 5.0], device=device)

print("Addition:", a + b)
print("Dot product:", torch.dot(a, b))
# print("Element-wise multiply:", a * b)

Addition: tensor([6., 8.])
Dot product: tensor(23.)


In [ ]:
# Create two 3D tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Operations
print("Addition:", a + b)
print("Dot product:", torch.dot(a, b))
# print("Element-wise multiply:", a * b)

In [ ]:
# 3D tensor = batch of 2 matrices, each 2x2
C = torch.tensor([
    [[1, 2], 
     [3, 4]],
    # [[5, 6], 
    #  [7, 8]]
])

D = torch.tensor([
    [[1, 1], 
     [0, 1]],
    # [[2, 0], 
    #  [1, 2]]
])

# Operations
print("Element-wise addition:\n", C + D)
print("Element-wise multiplication:\n", C * D)
print("matrix multiplication multiplication:\n", torch.matmul(C, D))

Element-wise addition:
 tensor([[[2, 3],
         [3, 5]]])
Element-wise multiplication:
 tensor([[[1, 2],
         [0, 4]]])
Element-wise multiplication:
 tensor([[[1, 3],
         [3, 7]]])
